cfg = {
    "<program>": [["<global>", "<user_defined_function>", "chungus", "skibidi", "(", ")", "{", "<body>", "back", "0", "}"]],
    "<global>": [["<global_statement>", "<global>"],
                ["λ"]],
    "<global_statement>": [["<var_data_type>", "<identifier>", "=", "<global_val>", "<var_dec_tail>"],
                            ["<const_dec>", "<var_data_type>", "<identifier>", "=", "<var_dec_tail>"],
                            ["<d_structure>"]],
    "<global_val>": [["<list_assignment>"],
                     ["<predefined_value>"]],
    "<const_dec>": [["sturdy"],
                   ["λ"]],
    "<data_id>": [["<data_type>", "<identifier>"]],
    "<identifier>": [["IDENTIFIER", "<list_index>", "<struct_mem>"]],
    "<data_type>": [["chungus"], ["chudeluxe"], ["forsen"], ["forsencd"], ["lwk"], ["aura"], ["gng"]],
    "<list_index>": [["[", "<indexer>", "]"],
                     ["λ"]],
    "<indexer>": [["CHU_LIT"], ["<identifier>"], ["<num_expression>"], ["<userdeffunc_call>"]],
    "<struct_mem>": [[".", "<identifier>", "<struct_mem>"],
                      ["λ"]],
    "<literal>": [["<num_literal>"], ["FORSEN_LIT"], ["FORSENCD_LIT", "<stringCC>"], ["LWK_LIT"]],
    "<num_literal>": [["CHU_LIT"], ["CHUDEL_LIT"]],
    "<stringCC>": [["+", "FORSENCD_LIT", "<stringCC>"],
                   ["λ"]],
    "<user_defined_function>": [["<return_type>", "IDENTIFIER", "(", "<parameter>", "<next_param>", ")", "{", "<statement>", "}", "<global>", "<user_defined_function>"],
                                ["λ"]],
    "<return_type>": [["nocap"], ["<data_type>", "<dstruct_id>"]],
    "<parameter>": [["<data_id>"], ["λ"]],
    "<next_param>": [[",", "<parameter>", "<next_param>"],
                      ["λ"]],
    "<userdeffunc_call>": [["<type_conversion>", "IDENTIFIER", "(", "<arg>", "<next_arg>", ")"]],
    "<arg>": [["<predefined_value>"], ["λ"]],
    "<next_arg>": [[",", "<arg>", "<next_arg>"],
                    ["λ"]],
    "<expression>": [["<num_expression>"], ["<bool_expression>"]],
    "<num_expression>": [["<num_operand>", "<_arith_op>", "<num_operand>", "<num_expression_tail>"],
                         ["<type_conversion>", "(", "<num_expression>", ")"]],
    "<num_operand>": [["<type_conversion>", "<_unary_op>", "<num_val>", "<_prepost_op>"]],
    "<num_val>": [["<num_literal>"], ["<identifier>", "<ts_function>"]],
    "<num_expression_tail>": [["<_arith_op>", "<num_operand>", "<num_expression_tail>"],
                              ["λ"]],
    "<_unary_op>": [["-"], ["<_prepost_op>"], ["λ"]],
    "<_prepost_op>": [["++"], ["--"], ["λ"]],
    "<_arith_op>": [["+"], ["-"], ["/"], ["%"], ["*"]],
    "<bool_expression>": [["<relational_expression>"],
                          ["<log_open>", "<_log_op>", "<log_open>", "<log_expression_tail>"]],
    "<relational_expression>": [["<rel_operand>", "<_rel_op>", "<rel_operand>", "<rel_expression_tail>"]],
    "<rel_operand>": [["<type_conversion>", "<rel_operand_content>"]],
    "<rel_operand_content>": [["<num_literal>"], ["<identifier>", "<ts_function>"]],
    "<rel_expression_tail>": [["<_rel_op>", "<rel_operand>", "<rel_expression_tail>"],
                              ["λ"]],
    "<_rel_op>": [[">"], ["<"], [">="], ["<="], ["<_rel_eq_op>"]],
    "<_rel_eq_op>": [["=="], ["!="]],
    "<_log_op>": [["&&"], ["||"]],
    "<_not_op>": [["!"], ["λ"]],
    "<body>": [["<statement>", "<body>"],
               ["λ"]],
    "<statement>": [["<var_dec>"], ["yap", "(", "<print_arg>", ")"], ["back", "<predefined_value>"]],
    "<print_arg>": [["<print_arg1>", "<print_argN>"]],
    "<print_arg1>": [["FORSEN_LIT", "<stringCC>"], ["<predefined_value>"]],
    "<print_argN>": [[",", "<predefined_value>", "<print_argN>"], ["λ"]],
    "<type_conversion>": [["(", "<convert_type>", ")"],
                          ["λ"]],
    "<convert_type>": [["chungus"], ["chudeluxe"]]
}
