4/3/2025 
cfg = {
    "<program>": [[ "<global_dec>", "<user_def_func>", "<main>",]],
    "<global_dec>": [["ε"],
        ["<variable_declaration>", "nl", "<global_dec>"],
        ["<constant_vardec>", "nl", "<global_dec>"]],
    "<user_def_func>": [["ε"],
        ["fein", "<return_type>", "identifier", "(", "<parameter>", ")", "{", "nl", "<body>", "}", "nl", "<user_def_func>"]],
    "<main>": [["skibidi", "{", "nl", "<body>", "}"]],
    "<variable_declaration>": [["<data_id>", "<var_init>"]],
    "<constant_vardec>": [["sturdy", "<variable_declaration>"]],
    "<data_id>": [["<data_type>", "identifier"]],
    "<id>": [["identifier", "<index>"]],
    "<index>": [["ε"],
        ["[", "<expression>", "]"]],
    "<data_type>": [["chungus"],
        ["chudeluxe"],
        ["forsen"],
        ["forsencd"],
        ["lwk"]],
    "<return_type>": [["<data_type>"],
        ["nocap"]],
    "<var_init>": [["=", "<value>", "<var_init_tail>"]],
    "<var_init_tail>": [["ε"],
        [",", "identifier", "<var_init_tail>"]],
    "<value>": [["<expression>"],
        ["chat", "(", ")"],
        ["<list_value>"]],
    "<list_value>": [["[", "<list_content>", "]"],
        ["append", "(", "<arg>", ")"],
        ["insert", "(", "<expression>", ",", "<arg>", ")"],
        ["remove", "(", "<expression>", ")"]],
    "<list_content>": [["ε"],
        ["<arg>"]],
    "<parameter>": [["ε"],
        ["<data_id>", "<parameter_tail>"]],
    "<parameter_tail>": [["ε"],
        [",", "<data_id>", "<parameter_tail>"]],
    "<arg>": [["<expression>", "<arg_tail>"]],
    "<arg_tail>": [["ε"],
        [",", "<expression>", "<arg_tail>"]],
    "<body>": [["ε"],
        ["<global_dec>", "nl", "<body>"],
        ["<statement>", "nl", "<body>"],
        ["<id_stmt>", "nl", "<body>"]],
    "<statement>": [["ε"],
        ["<output>", "nl", "<statement>"],
        ["<if_statement>", "nl", "<statement>"],
        ["<switch_statement>", "nl", "<statement>"],
        ["<for_loop>", "nl", "<statement>"],
        ["<while_loop>", "nl", "<statement>"],
        ["<dowhile_loop>", "nl", "<statement>"],
        ["<return_statement>", "nl", "<statement>"],
        ["getout", "nl", "<statement>"],
        ["<id_stmt>", "nl", "<statement>"]],
    "<output>": [["yap", "(", "<print_arg1>", "<print_argN>",")"]],
    "<print_arg1>": [["<expression>"]],
    "<print_argN>": [["ε"],
        [",", "<expression>", "<print_argN>"]],
    "<if_statement>": [["tuah", "(", "<expression>", ")", "{", "nl", "<body>", "}", "nl", "<if_tail>"]],
    "<if_tail>": [["ε"],
        ["hawk", "<hawk_follow>"]],
    "<hawk_follow>": [["<if_statement>"],
        ["{", "nl", "<body>", "nl", "}"]],
    "<switch_statement>": [["lethimcook", "(", "<expression>", ")", "{", "nl", "<case_statement>", "}"]],
    "<case_statement>": [["ε"],
        ["caseoh", "<constant>", ":", "nl", "<body>", "<case_statement>"],
        ["npc", ":", "nl", "<body>"]],
    "<constant>": [["chungus_lit"],
        ["forsen_lit"]],
    "<for_loop>": [["plug", "(", "<for_initialization>", ";", "<expression>", ";", "<id_update>", ")", "{", "nl", "<body>", "}"]],
    "<while_loop>": [["jit", "(", "<expression>", ")", "{", "nl", "<body>", "}"]],
    "<dowhile_loop>": [["lil", "{", "nl", "<body>", "}", "nl", "jit", "(", "<expression>", ")"]],
    "<for_initialization>": [["<variable_declaration>"],
        ["<id_stmt>"]],
    "<return_statement>": [["back", "<return_value>"]],
    "<return_value>": [["ε"],
        ["<expression>"]],
    "<expression>": [["<expr_head>", "<expr_tail>"]],
    "<expr_head>": [["<term>", "<term_tail>"]],
    "<term>": [["<factor>", "<builtin_func>", "<factor_tail>"]],
    "<factor>": [["-", "<factor1>"],
        ["!", "<factor1>"],
        ["<factor1>"]],
    "<factor1>": [["<literal>"],
        ["<id>", "<id_factor_tail>"],
        ["<pre_operator>", "<id>"],
        ["(", "<oppar>"]],
    "<id_factor_tail>": [["<post_operator>"],
        ["(", "<func_call_arg>", ")"]],
    "<func_call_arg>": [["ε"],
        ["<arg>"]],
    "<oppar>": [["<typecast>", ")", "<term>"],
        ["<expression>", ")"]],
    "<pre_operator>": [["--"],
        ["++"]],
    "<post_operator>": [["ε"],
        ["<pre_operator>"]],
    "<builtin_func>": [["ε"],
        [".", "<builtin_func1>"]],
    "<builtin_func1>": [["taper", "(", ")"],
        ["ts", "(", ")"]],
    "<typecast>": [["chungus"],
        ["chudeluxe"]],
    "<factor_tail>": [["ε"],
        ["<factor_op>", "<factor>", "<factor_tail>"]],
    "<factor_op>": [["+"],
        ["-"],
        ["/"],
        ["*"],
        ["%"]],
    "<term_tail>": [["ε"],
        ["<term_op>", "<factor>", "<term_tail>"]],
    "<term_op>": [[">"],
        [">="],
        ["<"],
        ["<="],
        ["=="],
        ["!="]],
    "<expr_tail>": [["ε"],
        ["<expr_op>", "<expr_head>", "<expr_tail>"]],
    "<expr_op>": [["&&"],
        ["||"]],
    "<id_stmt>": [["<pre_operator>", "<id>", "<id_update_more>"],
        ["<id>", "<id_stmt_tail>"]],
    "<id_stmt_tail>": [["=", "<value>", "<id_update_more>"],
        ["<pre_operator>", "<id_update_more>"],
        ["(", "<func_call_arg>", ")"]],
    "<id_update>": [["<pre_operator>", "<id>", "<id_update_more>"],
        ["<id>", "<id_update_tail>"]],
    "<id_update_tail>": [["=", "<value>", "<id_update_more>"],
        ["<pre_operator>", "<id_update_more>"]],
    "<id_update_more>": [["ε"],
        [",", "<id_update>"]],
    "<literal>": [["chungus_lit"],
        ["chudeluxe_lit"],
        ["forsen_lit"],
        ["forsencd_lit"],
        ["lwk_lit"]],
}





cfg = {
    "<program>": [["<start>"]],
    "<start>":[["<global_declaration>", "<nl>", "<start>"],
        ["chungus", "<chungus_follow>"]],
    "<chungus_follow>":[["<identifier>", "<declaration_tail>", "<nl>", "<start>"], 
        ["skibidi", "(", ")", "{", "<nl>", "<body_main>", "back", "0", "<nl>", "}"]],
    "<global_declaration>":[["<constant_var>"], 
        ["<gldata_type>", "<identifier>", "<declaration_tail>"]],
    "<gldata_type>":[["forsen"], 
        ["forsencd"], 
        ["chudeluxe"], 
        ["lwk"],
        ["aura"],
        ["nocap"]],
    "<data_type>":[["chungus"],
        ["<gldata_type>"]],
    "<body>":[["ε"],
        ["<declaration>", "<nl>", "<body>"],
        ["<statement>", "<nl>", "<body>"],
        ["back", "<return_value>", "<nl>"]],
    "<body_main>":[["ε"],
        ["<declaration>", "<nl>", "<body_main>"],
        ["<statement>", "<nl>", "<body_main>"]],
    "<expression>":[["<operand>", "<expression_tail>"]],
    "<operand>":[["(", "<oppar>"],
        ["!", "<bool_operand>"],
        ["-", "<arith_operand>"],
        ["<prepost_operator>", "<identifier>"],
        ["chungus_lit"],
        ["chudeluxe_lit"],
        ["forsen_lit"],
        ["forsencd_lit"],
        ["lwk_lit"],
        ["<identifier>", "<post_operand>"]],
    "<bool_operand>":[["lwk_lit"],
        ["<identifier>"],
        ["(", "<expression>", ")"]],
    "<arith_operand>":[["chungus_lit"],
        ["chudeluxe_lit"],
        ["<identifier>"],
        ["(", "<expression>", ")"]],
    "<expression_tail>":[["ε"],
        ["<operator>", "<operand>", "<expression_tail>"],
        ["<dot_suffix>"]],
    "<post_operand>":[["ε"],
        ["<prepost_operator>"]],
    "<prepost_operator>":[["--"], 
        ["++"]],
    "<expression_tail>":[["ε"],
        ["<operator>", "<operand>", "<expression_tail>"],
        ["<dot_suffix>"]],
    "<value>":[["<list_value>"],
        ["<expression>"],
        ["chat","(",")"],
        ["<multi_struct_val>"]],
    "<multi_struct_val>":[["{", "<identifier>", "=", "<expression>", "<struct_init_tail>", "}"]],
    "<struct_init_tail>":[["ε"],
        [",", "<identifier>", "=", "<expression>", "<struct_init_tail>"]],
    "<dtype1>":[["chungus"],
        ["chudeluxe"]],
    "<oppar>":[["<dtype1>", ")", "<expression>"],
        ["<expression>", ")"]],
    "<operator>":[["+"], 
        ["- "], 
        ["*"], 
        ["/"], 
        ["%"],
        ["=="], 
        ["!="], 
        [">"], 
        ["<"], 
        [">="], 
        ["<="], 
        ["&&"], 
        ["||"]],
    "<identifier>":[["identifier", "<struct_id>", "<identifier_postfix>"]],
    "<identifier_postfix>":[["ε"], ["<dot_suffix>"], 
        ["(", "<postfix_content>", ")"]],
    "<struct_id>":[["ε"],
        ["identifier"]],
    "<dot_suffix>":[["<index>"], 
        [".", "<dot_suffix_content>"]],
    "<dot_suffix_content>":[["ts","(",")"], 
        ["taper","(",")"], 
        ["identifier", "<dot_suffix_tail>"]],
    "<dot_suffix_tail>": [["ε"],
        ["<dot_suffix>"]],
    "<postfix_content>":[["ε"],
        ["<parameter>"], 
        ["<arg>"]],
    "<index>":[["[", "<expression>", "]"]],
    "<arg>":[["<expression>", "<arg_tail>"]],
    "<arg_tail>":[["ε"],
        [",", "<expression>", "<arg_tail>"]],
    "<parameter>":[["<data_id>", "<parameter_tail>"]],
    "<parameter_tail>":[["ε"],
        [",", "<data_id>", "<parameter_tail>"]],
    "<data_id>":[["<data_type>", "<identifier>"]],
    "<constant_var>":[["sturdy", "<data_id>", "<var_initialization>"]],
    "<declaration>":[["<data_id>", "<declaration_tail>"],
        ["<constant_var>"],
        ["<id1>"]],
    "<declaration_tail>":[["ε"],
        ["<var_initialization>"],
        ["{", "<nl>", "<body>", "}"]],
    "<var_initialization>":[["=", "<value>", "<var_init_tail>"]],
    "<var_init_tail>":[["ε"],
        [",", "<identifier>", "<var_initialization>"]],
    "<statement>":[
        ["yap", "(", "<print_arg>", ")"],
        ["lethimcook", "(", "<identifier>", ")", "{", "<nl>", "<case_statement>", "}"],
        ["plug", "(", "<for_initialization>", ";", "<expression>", ";", "<id1>", ")", "{", "<nl>", "<body>", "}"],
        ["lil", "{", "<nl>", "<body>", "}", "jit", "(", "<expression>", ")"],
        ["jit", "(", "<expression>", ")", "{", "<nl>", "<body>", "}"],
        ["<if_statement>"],
        ["pause"]],
    "<if_statement>":[["tuah", "(", "<expression>", ")", "{", "<nl>", "<body>", "}", "<if_tail>"]],
    "<if_tail>":[["ε"],
        ["hawk", "<hawk_follow>"]],
    "<hawk_follow>":[["<if_statement>"],
        ["{", "<nl>", "<body>", "}"]],
    "<print_arg>":[["<expression>", "<print_argN>"]],
    "<print_argN>":[["ε"],
        [",", "<expression>", "<print_argN>"]],
    "<case_statement>":[["ε"],
        ["caseoh", "<constant>", ":", "<nl>", "<case_line>", "<case_statement>"],
        ["npc", ":", "<nl>", "<case_line>"]],
    "<for_initialization>":[["<data_id>", "<var_initialization>"],
        ["<id1>"]],
    "<constant>":[["chungus_lit"],
        ["forsen_lit"],
        ["lwk_lit"]],
    "<return_value>":[["ε"],
        ["<expression>"]],
    "<case_line>":[["ε"],
        ["<data_id>", "<var_initialization>", "<nl>", "<case_line>"],
        ["<id1>", "<nl>", "<case_line>"],
        ["<statement>", "<nl>", "<case_line>"],
        ["back", "<return_value>", "<nl>", "<case_line>"],
        ["getout", "<nl>", "<case_line>"]],
    "<list_value>":[["append", "(", "<arg>", ")"],
        ["insert", "(", "chungus_lit", ",", "<arg>", ")"],
        ["remove", "(", "chungus_lit", ")"],
        ["[", "<list_content>", "]"]],
    "<list_content>":[["ε"],
        ["<arg>"]],
    "<nl>":[["\n"]],
    #"<nl1>":[["ε"],["NL", "<nl1>"]],
    "<id1>":[["<prepost_operator>", "<identifier>"],
        ["<identifier>", "<id1_follow>"]],
    "<id1_follow>":[["<post_operand>"],
        ["<var_initialization>"]]
}